- lib/views/screens/login_screen.dart
- lib/views/screens/signup_screen.dart
Fixed the appearance of text field in presence of any validation errors.
**Previous behavior**:
**Current Behavior**:
> ux : fixed textfield appearance on validation error

- lib/services/api/room_api.dart
Closes #99 
Retries failed API requests (**503 Service Unavailable**) upto 3 times.
> feat: retry failed api requests

- lib/controllers/single_room_controller.dart
- lib/views/widgets/participant_block.dart
Closes #91 
Added a feature for Room admin to assign Moderators for the room.
Moderator actions:
- Make participants Speaker if they request to speak.
- Revert participants back to Listeners.
- Kick the participants from the room.
Room admin actions:
- All the actions that Moderators can do.
- Make participants Moderator.
- Remove the Moderator role.
> feat: Assigning moderators for the room

- lib/views/screens/login_screen.dart
**Solution**
```dart
onTap: () {
controller.emailController.clear();
controller.passwordController.clear();
controller.confirmPasswordController.clear();
Get.toNamed(AppRoutes.signup);
},
```
Closes #156
> fix: confirm password field persists value on navigation

- lib/utils/app_images.dart
Correct the name of the landingThirdImage to match the name of the image in the assets/images 
Fixes # (issue)
Just run the app and make sure that you are not getting the following exception in the logs:
**The following assertion was thrown resolving an image codec:
Unable to load asset: "assets/images/lading_third.png".
Exception: Asset not found
When the exception was thrown, this was the stack: 
#0      PlatformAssetBundle.loadBuffer (package:flutter/src/services/asset_bundle.dart:369:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:811:18)** 
> fix: Resolve typo mistake for landingThirdImage

- lib/views/screens/home_screen.dart
The Alignment of the no-room placeholder was not aligned to the center
<span>
Before
After
</span>
> No room placeholder alignment fixed

- android/app/src/main/AndroidManifest.xml
Fixes #185 
Changing the Project ID in the Android Manifest file solved the issue.
and I have noticed that there are still some bugs after redirecting the user to the app. It is probably because authentication is not properly handled. For this, I will raise a new issue after finding the cause of the bug.
https://github.com/AOSSIE-Org/Resonate/assets/141143426/6bf93ccd-8e4e-45a0-9f43-3a1d08986d25
Testing on the Android platform is successful. 
Testing on IOS is successful. Tested by @0xAdiyat . Thanks for help.
@chandansgowda 
Please review this PR,
Thanks
> Solved Missing Redirect Url Error (for both platforms)

- lib/controllers/auth_state_controller.dart
- lib/controllers/edit_profile_controller.dart
- lib/controllers/onboarding_controller.dart
Fixes #200 
I added logic to delete the old profile image of the user from storage as the user change or add a new profile image. This way we can maintain the usage of Storage and reduce the redundancy of profile images.
I tried other ways like storing image using user uid or email but it didn't work well so at last,
I created a new attribute in User Docs in the Database to store the UserProfileImageID and used it to delete the Old user image. 
I used DateTime millieSecondsSinceEpoch as a Unique ID for the profile image.
Everything at the front end and the database works fine. Shared some screenshots and screen-recording to review the changes.
https://github.com/AOSSIE-Org/Resonate/assets/141143426/0ba369ed-39f9-49d7-98cf-7a76336e4568
@chandansgowda Please review this.
> Added logic to delete old profile image as user add new profile image 

- lib/views/screens/home_screen.dart
Added media query and remove maxWidth Property on the refresh button to fix the right-overflow error getting displayed on home screen.
Fixes #209 
- [ ✔️ ] Bug fix (non-breaking change which fixes an issue)
Tested by running on my android device.
Please include screenshots below if applicable :
- [ ✔️ ] My code follows the style guidelines of this project
- [✔️ ] I have performed a self-review of my own code
- [ ✔️ ] My changes generate no new warnings
- [ ✔️ ] I have checked my code and corrected any misspellings
> fix: added media query to refresh button to fix right-overflow problem

- README.md
- lib/controllers/single_room_controller.dart
- lib/views/screens/room_screen.dart
- lib/views/widgets/loading_widget.dart
> feat: Alert before deleting or leaving the audio room

- lib/views/screens/edit_profile_screen.dart
Sure, based on the information you've provided, here's a possible pull request template:
---
Fixes #215 
This pull request addresses the issue by removing the delete button in the "Edit Profile" section when the profile picture is set to the default. This change aims to enhance user experience and prevent confusion.
I have tested this change by:
1. Navigating to the "Edit Profile" section.
2. Verifying that the delete button is hidden when the profile picture is set to the default.
3. Confirming that the delete button is still visible when a custom profile picture is set.
Screenshots:
> feat: Removed delete button for default profile picture

- lib/views/screens/discussions_screen.dart
There is error of null check on discussions page and that's why discussion page is not loading. This issue resolve that error
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
#220 
Bug
> fix: Null check Error on Discussion page

- android/app/src/main/AndroidManifest.xml
- lib/controllers/edit_profile_controller.dart
- pubspec.lock
- pubspec.yaml
This pull request introduces a new feature to address issue #207. The added feature allows users to crop, rotate, and magnify images when setting their profile picture.
The motivation behind this change is to enhance user experience and provide more flexibility when setting profile pictures. The ability to crop, rotate, and magnify images adds a layer of customization, allowing users to fine-tune their profile pictures to better suit their preferences.
The following tests were conducted to verify the changes:
1. Uploaded an image for profile picture setting.
2. Used the cropping feature to select a specific area of the image.
3. Tested the rotation functionality to ensure it works as expected.
4. Verified the magnification option and its impact on the image. …
> Added image crop feature

- lib/controllers/authentication_controller.dart
Fixes an issue where email authentication failed due to trailing spaces in email addresses. The changes ensure that trailing spaces are handled correctly during authentication.
Fixes #262 
- Implemented a trimming mechanism to remove trailing spaces from the email input before validation.
- Updated relevant validation functions to account for trimmed email inputs.
Conducted manual testing to verify that email inputs with trailing spaces no longer trigger errors.
> fix: prevent email auth failure due to trialing spaces

- android/app/build.gradle
- android/build.gradle
- android/settings.gradle
- lib/main.dart
- lib/utils/ui_sizes.dart
- lib/views/screens/create_room_screen.dart
- lib/views/screens/tabview_screen.dart
- pubspec.lock
- pubspec.yaml
This PR addresses the issue where a `Null check operator used on a null value` exception is thrown when trying to access `Get.width` and `Get.height` in the `UiSizes` class before the `BuildContext` is available.
The solution involves refactoring the `UiSizes` class to use `late` keyword for the size variables and initializing them in a new `init` method which is called after the `BuildContext` is available. 'MediaQuery' is used to get the screen sizes.
Fixes #288 
1. Refactored the `UiSizes` class to use `late` keyword for the size variables.
2.  Added an `init` method in `UiSizes` class to initialize the size variables using `MediaQuery`.
3. Called `UiSizes.init()` in the `build` method of the main widget.
1. Run the app to ensure it loads without throwing the `Null check operator used …
> [BugFix] Fix for Null Check Operator Used on a Null Value Exception in UiSizes Class

- lib/views/screens/splash_screen.dart
The app used to go complete black after the splash screen and other screens were not visible. There was a problem with navigating from splash screen to the next. I had imported app routes and added Get.offNamed(AppRoutes.landing) explicitly in the startAuthTimer() which helped in showing up the next screen.
Fixes #227 
before: 
https://github.com/AOSSIE-Org/Resonate/assets/114871036/68b94c17-12be-48e9-9322-a2745ad28f9f
after: 
https://github.com/AOSSIE-Org/Resonate/assets/114871036/3a98b5c8-ec3b-448c-b88f-b295a3d55049
> Fixed Black Screen issue

- lib/views/screens/onboarding_screen.dart
The username field on the onboarding_screen was giving error `general_argument_invalid, Invalid documentId param: UID must contain at most 36 chars. Valid chars are a-z, A-Z, 0-9, and underscore. Can't start with a leading underscore (400)`
This was happening due to a trailing space in the input which was not accounted for.
Fixes #268 
The code has been tested on my local machine using an android emulator and now the code is functioning as intended.
> [onboarding] trailing space username auth bug fix

- lib/utils/utils.dart
- lib/views/screens/edit_profile_screen.dart
Now, instead of using the deprecated OnWillPopScope, you can simply use PopScope to achieve the same functionality in a more efficient and future-proof way, 
also Refactored save changes Dialog as separated function in the app utils files to be separated from the ui code
Fixes #270
with my emulator 
here is  how app functions after the changes had done 
https://github.com/AOSSIE-Org/Resonate/assets/118139061/ced336de-b05b-4af5-8386-18b1bd84f220
> Enhance]:Replace-deperacted-OnWillPopScope-with-PopScope 

- lib/views/screens/login_screen.dart
**Problem:**
Bottom overflowed error when user is on login screen.
**Preview of the problem:**
**Reason:**
Hard Coded value of `height=780` is used for setting height(line 38 of login_screen.dart) of the Container containing  login screen elements
**Fix:**
Set `height=UiSizes.height_780` to implement responsive design instead of using hard coded values
#287 : [Bug:- Bottom overflowed error on login screen](https://github.com/AOSSIE-Org/Resonate/issues/287)
The changes are tested on Android Emulator (API 33: Pixel 8 Pro) and on Moto g40 Fusion(API 32). The changes fixes the bug without  raising any additional errors
**Preview After Fix:**
> Fix: Make login screen responsive by using height value from UiSizes

- lib/views/widgets/custom_card.dart
- pubspec.lock
**Problem:** 
When tiles on profile page are tapped the spalsh exceedes the visible boundry of the tiles.
**Preview of the problem:**
**Reason:**
CustomCard widget(from custom_card.dart) is used for creation of tiles on ProfileScreen(from profile_screen.dart).
So when the user taps the tiles the splash generated by the Inkwell of the CustomCard widget excceedes the visible boundries of the CustomCard causing overflow.
**Fix:**
Fixed splash overflow issue by setting clipBehaviour to clip.antiAlias in Card widget of CustomCard widget.
#284: [The splash radius of buttons on the profile page exceeds the border](https://github.com/AOSSIE-Org/Resonate/issues/284)  
The changes have been tested on android emulator(API 33 and 32) and do not cause any …
> Fix: Set clip behavior to antiAlias in CustomCard widget to fix splash overflow

- lib/views/screens/add_chapter_screen.dart
Implemented add chapter screen
> Implement add chapter screen

- lib/views/screens/chapter_play_screen.dart
- lib/views/screens/explore_screen.dart
- lib/views/screens/story_details_screen.dart
- lib/views/widgets/chapter_list_tile.dart
- lib/views/widgets/filtered_list_tile.dart
- lib/views/widgets/no_match_view.dart
Implemented story screen , chapter play screen , explore screen and lyrics screen
> Implement story screen , chapter play screen , explore screen and lyrics screen

- lib/models/message.dart
- lib/views/screens/room_chat_screen.dart
Updated chat screen to add more functionalities
- Message Replying: Users can reply to messages, with a tap to navigate to the original message.
- Smooth Scrolling: Automatically scrolls to referenced messages when tapped.
- Inline Editing: Double-tap to edit messages directly in the chat, with an "(edited)" label.
- Keyboard Shortcuts: "Enter" saves edits, "Esc" cancels them, and clicking outside cancels editing.
https://github.com/user-attachments/assets/6744ca4e-be3f-477b-9180-a930baaa2351
> Update chat screen to add more functionalities

- lib/utils/extensions/datetime_extension.dart
- lib/views/screens/notifications_screen.dart
- lib/views/screens/story_screen.dart
This PR enhances the Notifications UI to make it more visually appealing and intuitive. The update includes improved spacing, rounded borders, background colors, and icons for each notification type to create a more modern look similar to real app notifications. Mock data has been added to populate the list with diverse examples.
- Added card-like styling for each notification tile with rounded borders, padding, and shadow effects.
- Adjusted spacing for better readability, especially between avatar and text.
- Added icons for each notification type using a switch case, with color coding for quick identification.
- Updated background color of notification tiles to enhance visibility.
- Enhanced mock data to provide more variety in the notification list.
UI was tested by manually running …
> Enhance Notifications UI

- lib/views/screens/splash_screen.dart
This PR clearly addresses and resolves all the animated splash screen bugs and issues which currently exist
Fixes #370 Completely
This was Tested on a real Android 14.0.1 Redmi Note 10 Pro Device. Below is the Video Demonstrating the Same: 
https://github.com/user-attachments/assets/3e5e0c95-7f26-4927-9d3d-eb100bcfb2ee
Logs Generated: 
[logs.txt](https://github.com/user-attachments/files/17799545/logs.txt)
> fix: animated splash screen redirects context to null

- lib/utils/constants.dart
- lib/views/screens/contribute_screen.dart
This PR improves the app by adding the feature to redirect user of AOSSIE discord page, they can discuss various topic there and learn more about this open source initiative
This was tested on a real Android 14.0.1 Redmi Note 10 Pro device. Below is the video of the implementation: 
https://github.com/user-attachments/assets/48f064b7-602e-4717-a972-3cc12cdf49f7
> feat: the discord icon redirects to discord page of aossie

- lib/views/screens/create_chapter_screen.dart
- lib/views/screens/create_story_screen.dart
Fixes #410
This PR fixes the overflow error in Upload Cover Image section in _Create Story_ and _Create Chapter_ Screens
> Fixed Overflow Error in `create_story_screen` & `create_chapter_screen`

- lib/views/screens/email_verification_screen.dart
- lib/views/screens/profile_screen.dart
- pubspec.yaml
UI Improvements in profile_screen & email_verification_screen
Fixes #409 
> UI Improvements in `profile_screen` & `email_verification_screen` Fixes #409

- lib/views/screens/tabview_screen.dart
The icon of the center docked Floating Action Button now changes dynamically for a better UX as previously the icon remained the same on both the Home Screen and Explore Screen despite the button performing different functions.
Fixes #452 
The App was run and the icon was verified to change appropriately as intended without causing unforeseen issues or breaking anything else.
<div align="center">
</div>
> Made floating action button icon change dynamically

- lib/controllers/explore_story_controller.dart
- pubspec.lock
To fix #448 added an Extension method to the Color Class that converts a given color into it's hexcode so that future usage of the hex to reconstruct the color remains working
Fixes #448 
Changes were tested by running the app and verifying that Tint colors were converted and reconstructed as required.
> Added Extension Method for Color Class to convert Color to Hexcode

- lib/controllers/explore_story_controller.dart
- pubspec.lock
While uploading the covers for the chapters the object ID being passed to the uploadFileToAppwriteGetUrl function was incorrectly set to use StoryId for each photo instead of the ChapterId. This PR changes that to the correct ChapterId.
Fixes #444 
This change was tested by adding new Stories and Chapters to the app and the previously observed error was not found to be present anymore
> Correct the ID of the Covers being uploaded for the Story Chapters

- lib/utils/colors.dart
- lib/views/screens/explore_screen.dart
- lib/views/widgets/story_list_tile.dart
This PR adds a better representation for Story Genres in the List Tiles displaying stories within the Explore Screen Suggestions tab. 
Before: 
After:
Fixes #454 
This was tested by adding different stories of different genres:
> Add tags for genres in explore screen

- lib/themes/theme_controller.dart
- lib/themes/theme_screen.dart
Why: Improves UX by allowing users to save and switch between preferred themes quickly
Highlights:
Validates theme names before saving
Saves favorite themes separately in GetStorage
Follows GetX state management best practices
Maintains compatibility with existing theme logic
✅ Thoroughly tested and follows clean architecture principles
Fixes # 468
> Favorite Themes functionality to ThemeController

- android/app/build.gradle.kts
- android/gradle/wrapper/gradle-wrapper.properties
- android/settings.gradle.kts
- pubspec.yaml
This PR makes changes to the AGP and Kotlin versions that Resonate uses to fix version mismatches and compatibility issues. Additionally, it fixes an issue introduced by #483 where a static path is used to reference the audio_metadata_reader dependency.
App was compiled for release and compiled without issue
> AGP Version changes and Pubspec fix

- .github/workflows/update-project-structure.yml
To prevent the GitHub Actions workflow from failing when there are no changes to commit, I have modified the commit and push step to check if there are any changes before attempting to commit.
Fixes #498 
> fix: fixed workflow bug
