README.md

As of now, I have added the architecture finalized by the mentor to the readme file so that contributors can have a better idea of how things should be implemented. 
Related: #2 
Closes #17

Added architecture documentation

---

ios/Podfile.lock
lib/controllers/authentication_controller.dart
lib/controllers/profile_controller.dart
lib/main.dart
lib/models/resonate_user.dart
lib/routes/app_pages.dart
lib/routes/app_routes.dart
lib/utils/enums/gender.dart
lib/views/screens/login_screen.dart
lib/views/screens/onboarding_screen.dart
lib/views/screens/signup_screen.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml

Changes:
1. Global Theme Date for icons, button and text
2. form validation for login and signup
3. Onboarding Flow with Firestore and Firebase Storage for saving user custom info and profile image
https://user-images.githubusercontent.com/55342789/234592474-1d3d8b6b-9feb-4995-9738-66c510592df4.mp4

Ux improvements

---

ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
lib/controllers/authentication_controller.dart
lib/controllers/onboarding_controller.dart
lib/views/screens/login_screen.dart
lib/views/screens/onboarding_screen.dart
lib/views/screens/signup_screen.dart
pubspec.lock

This PR includes the following changes:
- Improved upload profile image logic - Closes #41 
- Added snackbar for wrong-password and user-not-found auth errors - Closes #48 
- Removed password validation in login screen - Closes #34 
- Added loading Indicators wherever required - Closes #42 
- Logic to prevent multiple touch on signin/signup button

Performance Improvements and UX Enhancements

---

README.md

I have made the following changes to the readme file.
1. Updated High Level Architecture ( discussed with @jddeep )
2. Added contributor guidelines
3. Updated Firebase Firestore Structure
4. Some more minor improvements

Updated readme with finalised architecture and contributor guidelines

---

lib/views/screens/create_room_screen.dart
lib/views/screens/tabview_screen.dart
pubspec.lock
pubspec.yaml

Rather than just a popup, I think a screen would be better for this purpose since we might add even more parameters like category etc in the future. Here is a screenshot of the same.

Developed Create Room screen UI

---

lib/controllers/tabview_controller.dart
lib/models/example.dart
lib/models/participant.dart
lib/views/screens/room_screen.dart
lib/views/screens/tabview_screen.dart
lib/views/widgets/participant_block.dart

A non dismissible modal bottom sheet is used to display the room screen which gives the user a better user experience than a simple room screen. I have just used some static data as of now.  Here is a screenshot of the same.

Developed Room Screen (Bottom Sheet) UI

---

lib/views/screens/create_room_screen.dart
lib/views/screens/home_screen.dart
lib/views/screens/profile_screen.dart
lib/views/screens/tabview_screen.dart

The first version of the application's user interface design is now developed and can be connected to the controllers.
Home Screen  |  Profile Screen | Create Room Screen          
:-------------------------:|:-------------------------:|:-------------------------:
Room Screen 
:-------------------------:
Closes #47

First version of App User Interface

---

lib/bindings/auth_splash_bindings.dart
lib/bindings/profile_binding.dart
lib/bindings/tabview_binding.dart
lib/controllers/auth_state_controller.dart
lib/controllers/authentication_controller.dart
lib/controllers/create_room_controller.dart
lib/controllers/onboarding_controller.dart
lib/controllers/rooms_controller.dart
lib/controllers/single_room_controller.dart
lib/controllers/tabview_controller.dart
lib/models/appwrite_room.dart
lib/models/participant.dart
lib/services/api/api_service.dart
lib/services/room_service.dart
lib/utils/constants.dart
lib/views/screens/home_screen.dart
lib/views/screens/profile_screen.dart
lib/views/screens/room_screen.dart
lib/views/screens/splash_screen.dart
lib/views/screens/tabview_screen.dart
lib/views/widgets/participant_block.dart
lib/views/widgets/room_tile.dart
pubspec.lock
pubspec.yaml

This PR includes the following changes:
1. Added Room service class to create, join, leave and delete room
2. Swipe to Refresh Room List in home screen
3. Added realtime stream to listen for room updates and trigger rebuild
4. Toggle mic on/off functionality
5. Added Room model and made changes to Participant model
6. UI/UX Improvements
Closes #78

Implemented Room Management + Realtime Stream

---

ios/Podfile.lock
lib/bindings/auth_splash_bindings.dart
lib/controllers/create_room_controller.dart
lib/controllers/rooms_controller.dart
lib/controllers/single_room_controller.dart
lib/models/appwrite_room.dart
lib/models/participant.dart
lib/routes/app_pages.dart
lib/services/room_service.dart
lib/views/screens/room_screen.dart
lib/views/widgets/participant_block.dart
lib/views/widgets/room_tile.dart
pubspec.lock
pubspec.yaml

This PR includes the following changes:
1. Admins can't leave the room rather they can delete the room.
2. If in any case, admin stops the app while in room, he can log back into the room as admin.
3. Listeners can raise/putdown hands to request speaker role in the room - Closes #89 
4. Admins can accept speaker requests and promote a listener to speaker
5. Admins can also demote a speaker to listener
6. Admins can kick out participants in their room
https://github.com/AOSSIE-Org/Resonate/assets/41890434/3ea99803-f97a-4004-ad63-7512b3baf6e7

Room Management Enhancements: Delete Room, Request Speaker Role, Admin Approval, and Kick out participant

---

lib/controllers/create_room_controller.dart
lib/controllers/rooms_controller.dart
lib/services/api/api_service.dart
lib/services/room_service.dart

Previously we were associating admin email to the created room. I have replaced it with UID in order to maintain consistency throughout the project. Closes #94

Replaced userEmail with appwrite UID

---

android/app/src/main/AndroidManifest.xml
ios/Podfile
ios/Podfile.lock
ios/Runner.xcodeproj/project.pbxproj
ios/Runner/Info.plist
lib/controllers/livekit_controller.dart
lib/controllers/rooms_controller.dart
lib/controllers/single_room_controller.dart
lib/services/room_service.dart
pubspec.lock
pubspec.yaml

Closes #72 
First working development version of the Resonate is ready.
This is just a basic setup of livekit sdk for audio communication. This can be improved upon demand.

Integrated LiveKit WebRTC for Audio Communication

---

lib/controllers/network_controller.dart
lib/controllers/pair_chat_controller.dart
lib/controllers/single_room_controller.dart
lib/main.dart
lib/routes/app_pages.dart
lib/routes/app_routes.dart
lib/utils/constants.dart
lib/views/screens/pair_chat_screen.dart
lib/views/screens/pairing_screen.dart
lib/views/screens/profile_screen.dart
lib/views/screens/tabview_screen.dart
lib/views/widgets/no_connection_dialog.dart
lib/views/widgets/pair_chat_dialog.dart
pubspec.lock
pubspec.yaml

This pull request introduces a significant enhancement to our application by implementing a comprehensive Pair Chat Management UI and Controller. This feature empowers users with an intuitive interface for managing and engaging in pair chats, fostering enhanced communication and collaboration. Partially resolves #114 
- Developed a modern and user-friendly Pair Chat Management User Interface (UI) that allows users to initiate, monitor, and actively participate in pair chats.
- Created a dedicated controller to manage the underlying logic and functionality of pair chat interactions, ensuring smooth communication and synchronization between users.
- Integrated the UI seamlessly with the existing application architecture, leveraging a modular design approach to minimize disruptions to the …

Implemented Pair Chat Management UI and Controller

---

lib/controllers/rooms_controller.dart
lib/controllers/single_room_controller.dart
lib/services/room_service.dart

1. Fixed inconsistencies in participant list - Closes #96 
2. Fixed issue where even the deleted rooms were being displayed in rooms list
3. Added loading indicator while deleting a room

Fixed known issues + Improved UX

---

lib/utils/constants.dart

chore: update function constants

---

lib/controllers/pair_chat_controller.dart
lib/views/screens/pair_chat_screen.dart

feat: add identity disclosure functionality in pair chats

---

README.md

Updated readme to add contribution section
fixes #166

docs: added contribution section

---

ios/Runner/Info.plist
lib/controllers/edit_profile_controller.dart
lib/controllers/onboarding_controller.dart
lib/routes/app_pages.dart
lib/routes/app_routes.dart
lib/services/appwrite_service.dart
lib/themes/themes.dart
lib/views/screens/edit_profile_screen.dart
lib/views/screens/profile_screen.dart

Fixes #93 
**Features:**
- Change Profile Picture - With the options of 
- Select From Camera, 
- Gallery or 
- Remove Profile Picture.
- Change User Display Name
- Change Username
- Save changes
- One dialogue box to alert the user if there are Unsaved Changes
I have also created Logic for **deleting the old username** from the database as the user **creates a new one**. So the old username can be **re-used**.
Display name and Username are properly **validated** and **username availability** is also checked.
Here's a zip file containing all the screenshots and screen recordings.
[Edit Profile - Vrund Raval.zip](https://github.com/AOSSIE-Org/Resonate/files/12873456/Edit.Profile.-.Vrund.Raval.zip)

Implemented Edit User Profile Feature

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/documentation_issue.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/PULL_REQUEST_TEMPLATE.md
SECURITY.md

docs: Added docs for community standards.

---

lib/views/screens/profile_screen.dart

Fixed issue #186 
@chandansgowda Please review it.

fix: removed blank space from the user profile picture and removed overflow of email verification icon.

---

docs/store_listing/description.md

Added the App Description as mentioned.

docs: description for store listing

---

lib/views/screens/onboarding_screen.dart

corrected the colliding text errors

fix: text overflow in onboarding screen

---

lib/views/widgets/no_connection_dialog.dart

Fix : #177
Fixed it using a SingleChildScrollView and Center Widget.
https://github.com/AOSSIE-Org/Resonate/assets/92450890/ef432a56-4bbf-4b3c-8d82-cbd06ab48de5

fix: Resolve split-screen issue  #177

---

lib/views/screens/pair_chat_screen.dart
lib/views/screens/pairing_screen.dart
lib/views/widgets/pair_chat_dialog.dart
pubspec.lock

ui: improved pair chat screen

---

android/app/src/main/AndroidManifest.xml
lib/controllers/edit_profile_controller.dart
lib/themes/themes.dart
pubspec.lock
pubspec.yaml

Fixes #250 
The crop profile image screen UI was improved and Fixed elevated button in the edit profile screen.
Tested on an Android device and haven't made any changes that can affect the IOS device.
[ScreenShots.zip](https://github.com/AOSSIE-Org/Resonate/files/13927662/ScreenShots.zip)
https://github.com/AOSSIE-Org/Resonate/assets/141143426/dac935ce-9a6e-479f-b1da-1198e248a03f

ui: crop profile image screen improved

---

lib/utils/utils.dart
lib/views/screens/tabview_screen.dart

Enhanced the pop up ui by adding padding to the box and increasing the visibility of the button texts.
Fixes #236

Email verification pop-up ui

---

lib/controllers/authentication_controller.dart
lib/controllers/discussions_controller.dart

remove redundant initializations to null.
Fixes #271 
Tested manually. No errors were encountered after the changes were made.

fix: remove redundant initializations to null.

---

lib/views/widgets/discussion_tile.dart
pubspec.lock

overflow exception in discussion tile
Fixes #278 
tested manually by running app on android emulator. 
##before
##After

FIX: prevent overflow exception in discussion tile

---

lib/controllers/tabview_controller.dart
lib/views/screens/room_screen.dart

This pull request resolves the issue where a null value was causing a subtype error in a function with a return type of Future<void>. By updating the return type to Future<dynamic>, the function can now handle null return values without any errors.
Fixes #292
updating the return type to Future<dynamic>, the function can now handle null return values without any errors.
- tested manually on my emulator
before bug fixes :
After
https://github.com/AOSSIE-Org/Resonate/assets/118139061/77f32e52-2b4e-498a-9bc5-6a4c1dc5edc7

 Handle null return value in Future<void> function

---

lib/controllers/authentication_controller.dart
lib/routes/app_pages.dart
lib/routes/app_routes.dart
lib/services/appwrite_service.dart
lib/views/screens/forgot_password_screen.dart
lib/views/screens/login_screen.dart
lib/views/screens/reset_password_screen.dart

Forgot password feature was implemented, once user enters their email, if an account exists, reset link is sent to their mail. Appropriate error handling is also implemented.
Fixes #245 
https://github.com/AOSSIE-Org/Resonate/assets/114871036/60be28eb-b20a-4aa0-9ad0-b47cb64dcce9
As this mail is sent on using local-host for testing purposes, the newPassword screen can be accessed by uncommenting out a line of code which is mentioned in the resetPassword method. We can do this in the later stages of the application, before deploying the app.

feat: Implemented Forgot Password

---

lib/views/screens/profile_screen.dart

fix overflow when user click on verify email text in profile screen 
Fixes #295
by my emulator 
before
after 
https://github.com/AOSSIE-Org/Resonate/assets/118139061/ef88a1e8-5764-45df-b98e-a4f5dcf07ade

Handle overflow exception from profile screen

---

lib/services/appwrite_service.dart

issue-:#211
Added: Check server status method added for the appwrite server before going to the home screen.
Fixes #211
- [x ] New feature (non-breaking change which adds functionality)
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have checked my code and corrected any misspellings

Added: Check server status method added for the appwrite server before going to the home screen.

---

lib/controllers/auth_state_controller.dart
lib/controllers/authentication_controller.dart
lib/controllers/discussions_controller.dart
lib/controllers/single_room_controller.dart
lib/main.dart
lib/routes/app_pages.dart
lib/themes/themes.dart
lib/utils/ui_sizes.dart
lib/utils/utils.dart
lib/views/screens/create_room_screen.dart
lib/views/screens/discussions_screen.dart
lib/views/screens/email_verification_screen.dart
lib/views/screens/forgot_password_screen.dart
lib/views/screens/landing_screen.dart
lib/views/screens/login_screen.dart
lib/views/screens/profile_screen.dart
lib/views/screens/reset_password_screen.dart
lib/views/screens/room_screen.dart
lib/views/screens/tabview_screen.dart
lib/views/widgets/color_selection_widget.dart
lib/views/widgets/discussion_tile.dart
lib/views/widgets/loading_widget.dart
lib/views/widgets/pair_chat_dialog.dart
lib/views/widgets/room_tile.dart
pubspec.lock

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)

bringing dev and master on the same page

---

devtools_options.yaml
lib/controllers/change_email_controller.dart
lib/controllers/edit_profile_controller.dart
lib/controllers/email_verify_controller.dart
lib/routes/app_pages.dart
lib/routes/app_routes.dart
lib/services/appwrite_service.dart
lib/views/screens/change_email_screen.dart
lib/views/screens/edit_profile_screen.dart
lib/views/screens/profile_screen.dart
lib/views/screens/signup_screen.dart
pubspec.lock

Added functionality to change user email address. user will have to again verify email if they update their email address. email is changed in authentication and databases. and consistency is maintained.
Fixes #320 
I tested it in many ways and tried all possible cases. and everything works fine. and the screenshots and screen-recording of tests are added below.
[Screenshots.zip](https://github.com/AOSSIE-Org/Resonate/files/14896261/Screenshots.zip)
https://github.com/AOSSIE-Org/Resonate/assets/141143426/57503cf4-55cd-4fd0-b13d-918cfae8e4cc

feat: added feature to change user email address

---

.github/WORK_FLOW/greet_contributors.yml

Implemented a GitHub Action to automatically greet new pull request (PR) and issue creators,
Fixes # #247 

fix: #247 added yaml file

---

lib/models/category_model.dart
lib/models/sony_model.dart
lib/models/story_model.dart
lib/routes/app_pages.dart
lib/routes/app_routes.dart
lib/views/screens/explore_screen.dart
lib/views/screens/tabview_screen.dart
lib/views/widgets/category_card.dart
lib/views/widgets/song_list_tile.dart
lib/views/widgets/story_card.dart

Implement explore screen with dummy data

Implement explore screen with dummy data 💯 

---

lib/controllers/rooms_controller.dart
lib/controllers/single_room_controller.dart
lib/controllers/upcomming_rooms_controller.dart
lib/services/api_service.dart
lib/views/screens/home_screen.dart
lib/views/widgets/live_room_tile.dart
lib/views/widgets/upcomming_room_tile.dart
pubspec.lock

Tested the new home-screen with new upcomingRoom and Room tiles with live data after integrating the controllers and business logic into it from appwrite self-hosted, made it work

Integrated Controllers with the Home Screen 

---

lib/controllers/auth_state_controller.dart
lib/controllers/upcomming_rooms_controller.dart
lib/models/appwrite_upcomming_room.dart

Made FCM push notifications compatible from the client side and cloud functions side with the new architecture of the upcomingRooms Database

Made FCM compatible with new architecture of upcomingRooms Database

---

lib/views/screens/create_room_screen.dart
lib/views/widgets/profile_avatar.dart
lib/views/widgets/upcomming_room_tile.dart

improved room screen UI a little ensuring looks decent on both light and dark themes

feat: tweaked the new room screen a little

---

lib/views/screens/no_room_screen.dart

Converting reference of Discussion to Upcoming room

---

lib/views/screens/profile_screen.dart

Updated profile screen to include creator profile and code refactor

Update profile screen to include creator profile and code refactor

---

lib/main.dart
lib/routes/app_pages.dart
lib/routes/app_routes.dart
lib/views/screens/create_chapter_screen.dart
lib/views/screens/create_story_screen.dart
pubspec.lock
pubspec.yaml

Implemented create story and create chapter screens

Implement create story and create chapter screens

---

lib/views/screens/category_screen.dart
lib/views/widgets/category_card.dart

Implement Category Screen

---

lib/controllers/single_room_controller.dart
lib/views/screens/add_chapter_screen.dart
lib/views/screens/home_screen.dart
lib/views/screens/room_screen.dart
lib/views/widgets/live_room_tile.dart
lib/views/widgets/upcomming_room_tile.dart

Fixes made
Upcoming Rooms and Rooms inconsistency caused by improper use of Get.put() method: solved 
Add Story Chapter screen error if newly added chapter given a custom cover image: solved
Null Check Operator on Null value due to width not being defined in the Rooms screen on delete: solved

Solved some bugs and inconsistencies

---

lib/controllers/onboarding_controller.dart
lib/controllers/single_room_controller.dart
lib/utils/constants.dart
lib/views/screens/onboarding_screen.dart
lib/views/widgets/snackbar.dart
pubspec.lock

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)

userName unavailable message showing

---

lib/views/screens/about_app_screen.dart

This PR adds a feature of Sharing the App locally and Improvises the UI Layout of About Screen.
This was test on a real Android 14.0.1 Redmi Note 10 Pro device. Below are some screenshots: 
Old | New | Shared Link
--- | --- | ---

feat: added share-app-feature and improved ui

---

lib/views/screens/email_verification_screen.dart

There was a bracket missing in email_verification_screen.dart , This PR fixes it.
- [] I have made corresponding changes to the documentation

Bug: there is an unclosed bracket in email_verification_screen

---

lib/controllers/chapter_player_controller.dart
lib/views/screens/chapter_play_screen.dart
lib/views/screens/story_screen.dart
lib/views/widgets/chapter_player.dart

Complete UI of Chapter Play Screen was reworked to include a better scrolling experience and overall much better UI/UX
Fixes #455 
All previous features were verified to be working in the rework and exception handling for edge cases was also verified
https://github.com/user-attachments/assets/eede7ad3-af57-48de-9422-efbbcda356fc

Complete Chapter Player UI Overhaul

---

lib/views/screens/profile_screen.dart

This PR resolves the issue where the settings icon inside the circular button next to the “Edit Profile” button was not visible in any theme. The problem was due to the icon color matching the background color across all themes, resulting in the icon being hidden from view.
- Updated the icon color to dynamically adapt based on the active theme (light/dark), ensuring visibility.
- Confirmed that the icon now properly contrasts with the background in all supported themes.
Fixes #436
- Manually tested the settings icon visibility across all supported themes (light, dark, system default).
- Verified that the icon is now clearly visible and maintains sufficient contrast with the background.
- Checked on different screen sizes to ensure consistent …

Fix: Settings Icon Not Visible in Circular Button Across Themes

---

lib/controllers/livekit_controller.dart

This implements an automatic reconnection mechanism for LiveKit rooms to handle network disruptions gracefully. Currently, when users lose connection to a room, they need to manually rejoin. This implementation adds automatic reconnection attempts with proper user feedback and state management using GetX.
The changes include:
- Automatic reconnection logic with configurable retry attempts
- Connection state tracking using GetX observables
- User feedback system for connection status
- Proper cleanup of reconnection attempts
- Enhanced error handling and logging
Fixes #419 
1. Network Disruption Tests:
- Simulated network disconnections using Chrome DevTools
- Verified reconnection attempts (3 times with 2-second intervals)
- Confirmed proper user notifications during reconnection process …

Added reconnection logic to LiveKitController

---

ios/Podfile

updated the new version of ios platform

Updated Podfile

---

lib/controllers/livekit_controller.dart
lib/controllers/single_room_controller.dart
lib/views/screens/chapter_play_screen.dart
lib/views/screens/create_room_screen.dart
lib/views/screens/notifications_screen.dart
lib/views/screens/pair_chat_screen.dart
lib/views/screens/pairing_screen.dart
lib/views/screens/room_screen.dart
lib/views/screens/settings_screen.dart
lib/views/screens/story_screen.dart
lib/views/screens/tabview_screen.dart
lib/views/widgets/live_room_tile.dart
lib/views/widgets/pair_chat_dialog.dart
pubspec.lock

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #463 (issue)

fix: Resolve color.withOpacity() deprecation warnings

---

lib/themes/theme_controller.dart
lib/themes/theme_screen.dart

- Validate stored theme against Themes enum Remove unnecessary conditional rendering
- Add classic theme fallback Fixes #466
- Implements theme validation as per #466 
- Removed redundant 'none' state check
- Added enum value verification
| Device | OS | Result |
|--------|----|--------|
| Android Emulator | 34 | Pass |
| iOS Simulator | 17.4 | Pass |" \
--base main \
--head theme/validation-fixes \
--label "bug,gsoc2025" \
--reviewer "resonate-team/maintainers
Fixes # 466

fix(theme): Validate stored theme values and cleanup rendering

---

TRANSLATIONS.md

This PR adds a TRANSLATIONS.md doc for new contributors

docs: Add Translations,md for new contributors to add translations

---

README.md

Added Play Store Feature Graphic in Readme
Fixes #486 

Added play store feature graphic in Readme

---

.github/workflows/greet_contributors.yml

Changed pull_request to pull_request_target for proper fork permissions and added contents: read permission
Fixes #497 

Fix Greet Contributor Workflow 

---

ONBOARDING.md

Updated outdated Git Repo linked for Backend in Onboarding.md
Fixes #514

Fix: backend repo links in onboarding document
